@api = http://localhost:3000/categoria_equipos

GET {{api}}


###
GET {{api}}/1

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
    "nombre":"Equipo-119", 
    "descripcion": "computadora"
}

###
DELETE {{api}}/1

###
PUT {{api}}/1
Content-Type: application/json

{
    "nombre": "Equipo-200"
}
